# Linter Options
options:
  merge-default-rules: false
  formatter: compact
  output-file: 'linters/sass-lint.txt'

# File Options
files:
  include: 'assets/scss/**/*.scss'

# Rule Configuration
rules:
  brace-style:
    - 1
    -
      - style: 1tbs
  declarations-before-nesting: 1
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  final-newline: 1
  hex-length: 1
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 1
    -
      size: 2
  leading-zero:
    - 1
    -
      include: true
  mixins-before-declarations:
    - 1
    -
      exclude:
        - breakpoint
  no-color-keywords: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-warn: 1
  no-debug: 1
  one-declaration-per-line: 1
  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
  space-after-bang:
    - 1
    -
      include: false
  space-after-colon: 1
  space-after-comma: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon:
    - 1
    -
      include: false
  space-between-parens:
    - 1
    -
      include: false
  trailing-semicolon: 1
  zero-unit:
    - 1
    -
      include: false
